apiVersion: v1
kind: Service
metadata:
  name: my-pack
  labels:
    app: my-pack
spec:
  type: ClusterIP
  selector:
    app: my-pack
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
